definitions:
  notificationcommands.RequestPushTokenDTO:
    properties:
      account-id:
        type: string
      push-token:
        type: string
    type: object
info:
  contact: {}
  description: |-
    Auth-service: https://api.curanest.com.vn/auth/swagger/index.html.
    Patient-service: https://api.curanest.com.vn/patient/swagger/index.html.
    Nurse-service: https://api.curanest.com.vn/nurse/swagger/index.html.
    Appointment-service: https://api.curanest.com.vn/appointment/swagger/index.html.
    Notification-service: https://api.curanest.com.vn/notification/swagger/index.html.
  title: Notification Service
  version: "1.0"
paths:
  /external/rpc/notifications/push-token:
    post:
      consumes:
      - application/json
      description: create/update push-token
      parameters:
      - description: push-token data to create/update
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/notificationcommands.RequestPushTokenDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: create/update push-token
      tags:
      - 'rpc: notifications'
  /ping:
    get:
      consumes:
      - application/json
      description: ping server
      produces:
      - application/json
      responses:
        "200":
          description: message success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: ping server
      tags:
      - ping
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
